# Header
menu:
  Home: /
  About: /index.html#about
  Team: /#team
  Blog: http://blog.trackfellas.com
  Sign up: /#signup
  Get in touch: /#contacts
rss: /atom.xml

# Content
fancybox: false

# Sidebar

# Miscellaneous
google_analytics: true
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: